# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 13306
    connection-timeout: 5000ms
    servlet:
        context-path: /

debug: false

spring:
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    mvc:
        #throw-exception-if-no-handler-found: true
        static-path-pattern: /static/**

    freemarker:
      suffix: .html
      content-type: text/html
      charset: UTF-8
      cache: false
      template-loader-path: classpath:/templates
      enabled: true

mydb:
    url: jdbc:mysql://localhost:3306/dataj4mysql?characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root

dataj4json:
    password: admin13306

